### PR TITLE
Add missing features in package DT

### PR DESCRIPTION
**Pull request by prosoitos**
- width and height (can be a bit buggy though)
- text formatting (through escaping html formatting code)
- borders
- multirow (but not multicolumn. so I made it a partial "yes")
- numeric formatting (not straightforward to achieve, I'll give you that :) )
- dplyr compatible (unless I misunderstand what that means)

### CODE REVIEW

**Comment by prosoitos** [comment]
I guess `alignment` is also possible in `DT` by escaping html code. And probably many other features are achievable this way too.
On the other hand, one might argue that any formatting added this way is not a feature of the package. But having that flexibility is a great asset though.

**Comment by hughjonesd** [comment]
Yes, escaping HTML/TeX etc. doesn't count.

Dplyr compatible means that `filter`, `select` and friends work - do they?

**Comment by hughjonesd** [comment]
Incidentally, I have thought about adding an `as_datatable` method. But I wonder if it would add much value and if `huxtable` formatting maps easily on to DT. Thoughts?

**Comment by prosoitos** [comment]
> Yes, escaping HTML/TeX etc. doesn't count.
Fair enough :smile:

> Dplyr compatible means that filter, select and friends work - do they?
I see. No, it doesn't.

I'll remove the text formatting and dplyr ticks then :slightly_smiling_face: 

> Incidentally, I have thought about adding an as_datatable method. But I wonder if it would add much value and if huxtable formatting maps easily on to DT. Thoughts?
I haven't yet played with `huxtable`, so it is hard for me to have thoughts on this at this point. Your package looks incredibly easy to use and flexible and I am **super excited** to give it a try. Note that I am no expert in `DT`. I just noticed that some features that I have used where missing in the comparison table, so I spent a bit of time exploring `DT`'s options more closely to try to submit a fair PR. `DT` does not implement all of `DataTables`'s options and features. Not sure what `as_datatable` would do exactly.

Being able to escape latex and html code is a sweet feature since it pushes the potential as far as the user's knowledge of those languages goes. I haven't seen anything like that in my very quick exploration of `huxtable`, but I don't know the package yet, so maybe there an equivalent, or maybe it really is unnecessary due to the extent of its built-in functionality.

**Comment by prosoitos** [comment]
Is there an easy way to print a rendered html table in a browser? The reason I use `DT` is as a replacement of `View()` (which looks pretty ugly in X11). Calling `datatable` on a variable opens a rendered html of that variable in a browser (with my setting. It could be in RStudio or elsewhere). It doesn't even save a rendered file as this opens from a temp file. Some easy filtering and sorting functionality of `DT` on the created webpage allows for a nice check.

I tried `huxtable` and I think that I will like it to create tables in pdf or html documents. But it doesn't work for quick explorations of data (`quick_html()` takes a very long very long time compared to `datatable()`, it saves a file that has to be opened, then deleted, and the html does not allow quick sorting, filtering, etc. interactively). So both play very different roles and could complement each others. So maybe `as_datatable()` might be worth it... Or adding a function to open a quick html rendering of a variable? :stuck_out_tongue:

**Comment by hughjonesd** [comment]
as_html?

David

**Comment by prosoitos** [comment]
Of course. I totally see that (and I will use it now instead of `xtable` when I output pdf of html files: it is a great package! Thanks for it!). If the idea of a quick viewing additional function is not appealing, I can keep using `DT` for that :slightly_smiling_face:

**Pull request merged**
