### PR TITLE
Fix (NA) for huxreg

### PR DESCRIPTION
**Pull request by mattfidler**
The current huxreg includes (NA) for estimates where the standard error is not calculated.  This pull request fixes this and provides a flexible way to post-process these values anything you would like.

## Before changes:
``` r
library(nlmixr)
library(huxtable)

pheno <- function() {
    # Pheno with covariance
  ini({
    tcl <- log(0.008) # typical value of clearance
    tv <-  log(0.6)   # typical value of volume
    ## var(eta.cl)
    eta.cl + eta.v ~ c(1, 
                       0.01, 1) ## cov(eta.cl, eta.v), var(eta.v)
                      # interindividual variability on clearance and volume
    add.err <- 0.1    # residual variability
  })
  model({
    cl <- exp(tcl + eta.cl) # individual value of clearance
    v <- exp(tv + eta.v)    # individual value of volume
    ke <- cl / v            # elimination rate constant
    d/dt(A1) = - ke * A1    # model differential equation
    cp = A1 / v             # concentration in plasma
    cp ~ add(add.err)       # define error model
  })
}

fit <- nlmixr(pheno, pheno_sd, "saem",control=list(print=0))
#> Compiling RxODE equations...done.
#> Calculating covariance matrix
```

    #> Calculating residuals/tables
    #> done.
    
    ## Since this is for a table output, you will probably want to adjust the separators
    options(broom.mixed.sep1=": ", broom.mixed.sep2=", ")
    
    huxreg(fit)
    #> Warning in FUN(X[[i]], ...): tidy() does not return p values for models of
    #> class data.frame; significance stars not printed.
    #> Calculating -2LL by Gaussian quadrature (nnodes=3,nsd=1.6)

    #> Warning in huxreg(fit): Unrecognized statistics: r.squared
    #> Try setting `statistics` explicitly in the call to `huxreg()`
    #> Warning in knit_print.huxtable(x, ...): Unrecognized output format "markdown". Using `to_screen` to print huxtables.
    #> Set options("huxtable.knitr_output_format") manually to "latex", "html", "rtf", "docx", "pptx", "md" or "screen".

─────────────────────────────────────────────────
(1)  
─────────────────────────
tcl 0.007   
(0.001)  
tv 1.415   
(0.076)  
sd\_\_eta.cl 0.496   
(NA)       
sd\_\_eta.v 0.392   
(NA)       
cor\_\_eta.v, eta.cl 0.986   
(NA)       
add.err 2.840   
(NA)       
─────────────────────────
N 155       
logLik -503.373   
AIC 1018.746   
─────────────────────────────────────────────────
\*\*\* p \< 0.001; \*\* p \< 0.01; \* p \< 0.05.

Column names: names, model1

<sup>Created on 2019-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Note the `(NA)` in the std error estimates

## After changes

``` r
library(nlmixr)
library(huxtable)

pheno <- function() {
    # Pheno with covariance
  ini({
    tcl <- log(0.008) # typical value of clearance
    tv <-  log(0.6)   # typical value of volume
    ## var(eta.cl)
    eta.cl + eta.v ~ c(1, 
                       0.01, 1) ## cov(eta.cl, eta.v), var(eta.v)
                      # interindividual variability on clearance and volume
    add.err <- 0.1    # residual variability
  })
  model({
    cl <- exp(tcl + eta.cl) # individual value of clearance
    v <- exp(tv + eta.v)    # individual value of volume
    ke <- cl / v            # elimination rate constant
    d/dt(A1) = - ke * A1    # model differential equation
    cp = A1 / v             # concentration in plasma
    cp ~ add(add.err)       # define error model
  })
}

fit <- nlmixr(pheno, pheno_sd, "saem",control=list(print=0))
#> Compiling RxODE equations...done.
#> Calculating covariance matrix
```

    #> Calculating residuals/tables
    #> done.
    
    ## Since this is for a table output, you will probably want to adjust the separators
    options(broom.mixed.sep1=": ", broom.mixed.sep2=", ")
    
    huxreg(fit)
    #> Warning in FUN(X[[i]], ...): tidy() does not return p values for models of
    #> class data.frame; significance stars not printed.
    #> Calculating -2LL by Gaussian quadrature (nnodes=3,nsd=1.6)

    #> Warning in huxreg(fit): Unrecognized statistics: r.squared
    #> Try setting `statistics` explicitly in the call to `huxreg()`
    #> Warning in knit_print.huxtable(x, ...): Unrecognized output format "markdown". Using `to_screen` to print huxtables.
    #> Set options("huxtable.knitr_output_format") manually to "latex", "html", "rtf", "docx", "pptx", "md" or "screen".

─────────────────────────────────────────────────
(1)  
─────────────────────────
tcl 0.007   
(0.001)  
tv 1.415   
(0.076)  
sd\_\_eta.cl 0.496   
       
sd\_\_eta.v 0.392   
       
cor\_\_eta.v, eta.cl 0.986   
       
add.err 2.840   
       
─────────────────────────
N 155       
logLik -503.373   
AIC 1018.746   
─────────────────────────────────────────────────
\*\*\* p \< 0.001; \*\* p \< 0.01; \* p \< 0.05.

Column names: names, model1

<sup>Created on 2019-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Note the lack of `(NA)` in the table

### CODE REVIEW

**Comment by mattfidler** [comment]
Note it passes everything but one appveyor instance, which seems to have some issue with finding github...

https://ci.appveyor.com/project/hughjonesd/huxtable/builds/24129532/job/vb5wnk0s4lvtxd87

**Comment by mattfidler** [comment]
Also note for me, the following happens:

```R
> ft  <- as_flextable(huxreg('Phenobarbitol'=fit));
Error in UseMethod("as_flextable") : 
  no applicable method for 'as_flextable' applied to an object of class "c('huxtable', 'data.frame')"
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  tidy() does not return p values for models of class data.frame; significance stars not printed.
2: In huxreg(Phenobarbitol = fit) : Unrecognized statistics: r.squared
Try setting `statistics` explicitly in the call to `huxreg()`
> ft  <- huxtable::as_flextable(huxreg('Phenobarbitol'=fit));
Warning messages:
1: In FUN(X[[i]], ...) :
  tidy() does not return p values for models of class data.frame; significance stars not printed.
2: In huxreg(Phenobarbitol = fit) : Unrecognized statistics: r.squared
Try setting `statistics` explicitly in the call to `huxreg()`
> ft  <- flextable::as_flextable(huxreg('Phenobarbitol'=fit));
Error in UseMethod("as_flextable") : 
  no applicable method for 'as_flextable' applied to an object of class "c('huxtable', 'data.frame')"
```

This is fixed by
```R
as_flextable <- function(x, ...) flextable::as_flextable(x, ...)
```
Added it to my pull request.

**Comment by mattfidler** [comment]
I also noticed some rows are now empty, this allows filtering of empty rows.

**Comment by mattfidler** [comment]
As Discussed in #109, I added the R object name instead of `(1)`, `(2)`, ...

**Comment by mattfidler** [comment]
Apparently the deparsing broke things.

**Comment by hughjonesd** [comment]
First of all, thank you very much for being willing to make a pull request. I appreciate it.

In general, it is a good idea to do a single topic branch for each change you want to make. So, one for fixing NA, one for  changing names, and so on. That way each can be discussed individually.

I'm not a huge fan of the transform function approach. I don't think it would have use apart from fixing NAs - in which case we should try and fix that problem specifically. In general, if models simply don't have standard errors, then you can just do `error_format = ""`. Your problem is that some coefficients have standard errors, others don't.

The ideal thing would be to use `na_string` for this. Unfortunately the error format cells have character type, not numeric type, because they may include more than one number. It might be possible to detect NAs before the call to `glue` – but then we don't know if people are using standard errors or confidence intervals, so we don't know which NAs matter… I'm not sure there is a way around this except to edit the huxtable manually after it is returned from `huxreg`.

**Comment by mattfidler** [comment]
I agree that I am not in love with the approach. I have an idea that can generalized to any format without the extra function.  I will update this pull later if it works.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mattfidler** [comment]
``` r
library(nlmixr)
library(huxtable)

pheno <- function() {
    # Pheno with covariance
  ini({
    tcl <- log(0.008) # typical value of clearance
    tv <-  log(0.6)   # typical value of volume
    ## var(eta.cl)
    eta.cl + eta.v ~ c(1, 
                       0.01, 1) ## cov(eta.cl, eta.v), var(eta.v)
                      # interindividual variability on clearance and volume
    add.err <- 0.1    # residual variability
  })
  model({
    cl <- exp(tcl + eta.cl) # individual value of clearance
    v <- exp(tv + eta.v)    # individual value of volume
    ke <- cl / v            # elimination rate constant
    d/dt(A1) = - ke * A1    # model differential equation
    cp = A1 / v             # concentration in plasma
    cp ~ add(add.err)       # define error model
  })
}

fit <- nlmixr(pheno, pheno_sd, "saem",control=list(print=0))
#> Compiling RxODE equations...done.
#> Calculating covariance matrix
```

    #> Calculating residuals/tables
    #> done.
    library(huxtable)
    ## Since this is for a table output, you will probably want to adjust the separators
    ## This gives sd: and cor: eta1, eta2
    options(broom.mixed.sep1=": ",
            broom.mixed.sep2=", ")
    
    tbl <- huxreg('Phenobarbitol'=fit,
                  statistics=c(N = "nobs", "Objective Function" = "OBJF", "logLik", "AIC"))
    #> Calculating -2LL by Gaussian quadrature (nnodes=3,nsd=1.6)

``` r

tbl %>%  print_screen(colnames=FALSE)
#> ─────────────────────────────────────────────────
#>                               Phenobarbitol      
#>                         ─────────────────────────
#>   tcl                                 0.007 ***  
#>                                      (0.001)     
#>   tv                                  1.415 ***  
#>                                      (0.076)     
#>   sd__eta.cl                          0.496      
#>   sd__eta.v                           0.392      
#>   cor__eta.v, eta.cl                  0.986      
#>   add.err                             2.840      
#>   N                                 155          
#>   Objective Function                721.875      
#>   logLik                           -503.373      
#>   AIC                              1018.746      
#> ─────────────────────────────────────────────────
#>   *** p < 0.001; ** p < 0.01; * p < 0.05.

## As a bonus invalid `error_format`s now produce warnings

tbl <- huxreg('Phenobarbitol'=fit, error_format="({std.error}){nonstandard.error}",
              statistics=c(N = "nobs", "Objective Function" = "OBJF", "logLik", "AIC"))
#> Warning in huxreg(Phenobarbitol = fit, error_format = "({std.error}){nonstandard.error}", : Unrecognized format columns: nonstandard.error
#> These will be replaced with an empty string.
#> Try changing `error_format` in the call to `huxreg()`

tbl %>%  print_screen(colnames=FALSE)
#> ─────────────────────────────────────────────────
#>                               Phenobarbitol      
#>                         ─────────────────────────
#>   tcl                                 0.007 ***  
#>                                      (0.001)     
#>   tv                                  1.415 ***  
#>                                      (0.076)     
#>   sd__eta.cl                          0.496      
#>   sd__eta.v                           0.392      
#>   cor__eta.v, eta.cl                  0.986      
#>   add.err                             2.840      
#>   N                                 155          
#>   Objective Function                721.875      
#>   logLik                           -503.373      
#>   AIC                              1018.746      
#> ─────────────────────────────────────────────────
#>   *** p < 0.001; ** p < 0.01; * p < 0.05.
```

<sup>Created on 2019-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mattfidler** [comment]
Ok, I changed the solution to be more general;  Some notes:
- Now it warns with invalid `error_format` specifications instead of having an error.
- It assumes that the error format is only `{variable.name}`, which I think is 99% of the use-cases.

**Comment by mattfidler** [comment]
The broom.mixed tidiers for `nlme` are not complete yet, or I would provide a nlme example (since it doesn't provide standard errors and is a part of the R distribution).

**Comment by hughjonesd** [comment]
Since error_format is a glue string, one workaround would be something
like: “{if (is.na(stderr)) ‘’ else stderr}”
-- 
Sent from Gmail Mobile

**Comment by hughjonesd** [comment]
I'm afraid I am still not a fan. Pre-parsing the glue string will cause problems when it is non-standard, which breaks the commitment given by the `huxreg` help. And a lot of code is being added to an already (too) complex function, to deal with a rare case. I think the glue workaround that I suggested above will have to do for now.

I feel bad about rejecting the work that you have put in, but I do so because in the long run I will have to maintain any code that I accept. 

If you feel like it, now that you know the code, why not try one of the issues that has a help wanted tag?

**Comment by mattfidler** [comment]
Thank you for your consideration.

I think you have a good point. I respect that. If you wish to close this issue, it your choice (and is a good one).

I of course think that is good to think these things through.  In my opinion, this is not an edge case.  The nonlinear mixed effects modeling community is large and will be growing larger in R. My field entirely uses nonlinear mixed effects models.  

I also believe the Bayesian stan world does not provide standard errors for random effects (I will have to check this). 

If your main issue is the non-standard cases, I know how to fix them and can provide test cases if you wish (at the cost of additional complexity).

If your main issue is maintenance and additional code-complexity, I cannot fix that.

Just a note, my team and I will be teaching non-linear mixed effects modeling to lower and middle income countries; If I use the code you are suggesting it may confuse them from the heart of non-linear mixed effects modeling and report generation.  They may get bogged down and ask the instructors about how to add some simple features to the table (like CIs) and with the comparatively complex user code they possibly get confused.  When they get back to their homes/offices/etc, they may even ask you questions that could be avoided (even with your warning message on github).

As for your offer for me to fix some of the "help-wanted" issues, I am flattered.  However, like you I need to stay true to my main mission, which is nonlinear mixed effects modeling in R.  None of your issues touch on that field, so I must graciously decline.  If you see any "help-wanted" that touch on this, feel free to loop me in.

**Comment by hughjonesd** [comment]
OK. I’ll close for now, but remain open to future pull requests.

**Comment by mattfidler** [comment]
Ok.  To be clear you are ope. To pull requests on different topics.

You probably should fix the flextable embedded in this issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
